import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of service',
  description: 'Bench client service terms: measurement services, data rights, methodology shield, liability.',
  alternates: { canonical: '/legal/terms' },
}

/**
 * DRAFT — pending review by a practising lawyer (Moses) before go-live.
 * The 3-category data-rights clause (§5) is the load-bearing part: client
 * inputs / client model outputs / Bench-owned evaluations & gold standards.
 */

export default function TermsPage() {
  return (
    <section className="section section--flush">
      <div className="shell" style={{ paddingTop: 'var(--space-section)', paddingBottom: 'var(--space-section)' }}>
        <p className="eyebrow">Legal · client service terms</p>
        <h1 className="title">Terms of service.</h1>
        <p className="small" style={{ marginBottom: '2.5rem' }}>
          <span className="chip chip--warn">Draft — subject to counsel review before first engagement</span>
        </p>

        <div className="prose" style={{ maxWidth: '72ch' }}>
          <h2 className="heading">1. What Bench provides</h2>
          <p>
            Bench (operated by BizLegal AI / DOR INNOVATIONS, &ldquo;we&rdquo;)
            provides measurement and benchmarking services for AI systems that
            perform legal tasks: structured evaluation of client-submitted
            model outputs against versioned, jurisdiction-specific test
            materials, producing scores, error classifications, corrections,
            and remediation guidance (the &ldquo;Services&rdquo; and the
            resulting &ldquo;Reports&rdquo;).
          </p>

          <h2 className="heading">2. What Bench does not provide</h2>
          <p>
            The Services and Reports are not legal advice, are not a legal
            opinion on any matter, and do not create an attorney-client
            relationship. Bench is not a law firm and does not operate a lawyer
            referral service. Experts engaged by Bench work for Bench as
            independent contractors on analytical tasks; no client acquires any
            relationship with, or claim against, any individual expert.
          </p>

          <h2 className="heading">3. Fees</h2>
          <p>
            Services are provided for flat fees stated at order time. Fees are
            for measurement work and are not contingent on results. Except as
            stated in a signed order, fees are non-refundable once evaluation
            work has begun. Prices exclude VAT and similar taxes where
            applicable.
          </p>

          <h2 className="heading">4. Client materials and confidentiality</h2>
          <p>
            We treat client-submitted materials and client-identified results
            as confidential, use them only to deliver the Services, and retain
            them for twelve (12) months from delivery unless a shorter period
            is agreed or deletion is requested earlier, after which they are
            deleted. We never publish client-identified scores or results.
          </p>

          <h2 className="heading">5. Data rights — three categories</h2>
          <p>
            The parties distinguish three categories of data, with different
            ownership:
          </p>
          <p>
            <strong>(a) Client Inputs.</strong> Materials the client submits
            (prompts, documents, configuration, product information) remain the
            client&apos;s property. We receive a licence to use them solely to
            deliver the Services.
          </p>
          <p>
            <strong>(b) Client Model Outputs.</strong> Outputs generated by the
            client&apos;s AI system remain the client&apos;s property (or that
            of its licensors). We receive a licence to reproduce and analyse
            them solely to deliver the Services and, in anonymized and
            aggregated form only, to develop industry benchmarks and quality
            intelligence, provided no client-confidential information,
            proprietary model architecture, or identifiable business data is
            disclosed.
          </p>
          <p>
            <strong>(c) Bench Evaluation Materials.</strong> The evaluation
            rubrics, scoring data, error classifications, gold-standard answers
            and corrections, benchmark items, and all derived benchmark
            materials are created by Bench, are and remain the exclusive
            property of Bench, and are licensed to the client for its internal
            use as part of the Report. For clarity, a gold-standard answer
            states what the law is; it is authored by Bench&apos;s experts and
            does not derive from, incorporate, or disclose Client Inputs or
            client-confidential information.
          </p>

          <h2 className="heading">6. Methodology; no warranty of outcomes</h2>
          <p>
            Reports measure a defined test set, against a named benchmark
            version, at a stated point in time, under the methodology published
            at bench.bizlegal-ai.com/methodology. Reports are not a
            certification, not an audit under any statutory standard, and not a
            warranty that the measured system is safe, accurate, or compliant
            in production. AI systems change; a measurement is a snapshot.
          </p>

          <h2 className="heading">7. Liability</h2>
          <p>
            To the maximum extent permitted by law, our aggregate liability
            arising out of or relating to an engagement is capped at the fees
            paid for that engagement, and neither party is liable for indirect,
            consequential, or punitive damages. Nothing limits liability that
            cannot be limited by law.
          </p>

          <h2 className="heading">8. General</h2>
          <p>
            Orders may be executed and delivered electronically. These terms,
            together with an order and the Data Processing Addendum where it
            applies, are the entire agreement for the Services. Governing law
            and forum are stated in the order form.
          </p>

          <p className="footnote">
            Questions: team@bizlegal-ai.com · Data processing:{' '}
            <a href="/legal/dpa" style={{ borderBottom: '1px solid var(--rule)' }}>/legal/dpa</a>
          </p>
        </div>
      </div>
    </section>
  )
}
