import { schedules } from "@trigger.dev/sdk";
import { createClient } from "@supabase/supabase-js";
import { Resend } from "resend";

/**
 * weekly-newsletter (M.6 lite)
 *
 * Every Monday 13:00 UTC: pull everything the content engine published in
 * the last 7 days from `published_content` (migration 20260906), compose an
 * HTML summary grouped by product, and email it to the founder via Resend.
 *
 * Deliberately defensive:
 *  - Missing RESEND_API_KEY / NEWSLETTER_FROM / FOUNDER_EMAIL → the composed
 *    newsletter is logged and the run exits cleanly (no throw).
 *  - Missing published_content table → logged, empty newsletter, clean exit.
 *
 * Deferred from full M.6: milestone case-study emails (parts 1–3) and
 * weekly comparison posts (part 4) — those need the customer-milestone
 * source and n8n rendering, neither of which exists yet.
 */

interface PublishedRow {
  id: string;
  product: string | null;
  content_type: string | null;
  title: string | null;
  url: string | null;
  platform: string | null;
  published_at: string;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function composeHtml(rows: PublishedRow[], windowStart: Date, windowEnd: Date): string {
  const fmt = (d: Date) => d.toISOString().slice(0, 10);
  const byProduct = new Map<string, PublishedRow[]>();
  for (const row of rows) {
    const key = row.product ?? "uncategorized";
    const list = byProduct.get(key) ?? [];
    list.push(row);
    byProduct.set(key, list);
  }

  const sections: string[] = [];
  if (rows.length === 0) {
    sections.push("<p><em>Nothing was published this week.</em></p>");
  } else {
    for (const [product, items] of Array.from(byProduct.entries()).sort((a, b) => b[1].length - a[1].length)) {
      const lis = items
        .map((item) => {
          const label = escapeHtml(item.title ?? item.url ?? "(untitled)");
          const meta = [item.content_type, item.platform].filter((x): x is string => Boolean(x)).map(escapeHtml).join(" · ");
          const link = item.url ? `<a href="${escapeHtml(item.url)}">${label}</a>` : label;
          return `<li>${link}${meta ? ` <span style="color:#888">(${meta})</span>` : ""}</li>`;
        })
        .join("\n");
      sections.push(`<h2 style="margin:18px 0 6px">${escapeHtml(product)} (${items.length})</h2>\n<ul>\n${lis}\n</ul>`);
    }
  }

  return [
    `<h1>BizLegal Weekly — ${fmt(windowEnd)}</h1>`,
    `<p style="color:#888">${rows.length} piece(s) published ${fmt(windowStart)} → ${fmt(windowEnd)}.</p>`,
    ...sections,
    `<hr/><p style="color:#888;font-size:12px">Generated by the weekly-newsletter Trigger.dev task from <code>published_content</code>.</p>`,
  ].join("\n");
}

export const weeklyNewsletter = schedules.task({
  id: "weekly-newsletter",
  cron: { pattern: "0 13 * * 1", timezone: "UTC" }, // Mondays 13:00 UTC
  retry: {
    maxAttempts: 3,
    factor: 2,
    minTimeoutInMs: 1000,
    maxTimeoutInMs: 10_000,
    randomize: true,
  },
  run: async (payload) => {
    const windowEnd = payload.timestamp;
    const windowStart = new Date(windowEnd.getTime() - 7 * 24 * 60 * 60 * 1000);

    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL ?? process.env.SUPABASE_URL;
    const supabaseKey = process.env.SUPABASE_SERVICE_KEY ?? process.env.SUPABASE_SERVICE_ROLE_KEY;

    let rows: PublishedRow[] = [];
    if (!supabaseUrl || !supabaseKey) {
      console.warn("weekly-newsletter: Supabase env not configured; composing empty newsletter.");
    } else {
      const supabase = createClient(supabaseUrl, supabaseKey, {
        auth: { persistSession: false, autoRefreshToken: false },
      });
      const { data, error } = await supabase
        .from("published_content")
        .select("id, product, content_type, title, url, platform, published_at")
        .gte("published_at", windowStart.toISOString())
        .lte("published_at", windowEnd.toISOString())
        .order("published_at", { ascending: false })
        .limit(500);
      if (error) {
        // Table missing (migration 20260906 not applied) or any other query
        // failure: degrade to an empty newsletter instead of failing the run.
        console.warn(`weekly-newsletter: published_content query failed: ${error.message}`);
      } else {
        rows = (data ?? []) as PublishedRow[];
      }
    }

    const html = composeHtml(rows, windowStart, windowEnd);
    const subject = `BizLegal Weekly — ${windowEnd.toISOString().slice(0, 10)} (${rows.length} new)`;

    const resendKey = process.env.RESEND_API_KEY;
    const from = process.env.NEWSLETTER_FROM;
    const to = process.env.FOUNDER_EMAIL;
    if (!resendKey || !from || !to) {
      console.log(
        "weekly-newsletter: RESEND_API_KEY / NEWSLETTER_FROM / FOUNDER_EMAIL not all set — logging instead of sending.",
      );
      console.log(`subject: ${subject}`);
      console.log(html);
      return { sent: false, reason: "missing email env", items: rows.length };
    }

    const resend = new Resend(resendKey);
    const { error } = await resend.emails.send({ from, to, subject, html });
    if (error) {
      // Spec stop-condition: Resend API failure should surface, not be hidden.
      throw new Error(`weekly-newsletter: Resend send failed: ${error.message}`);
    }

    console.log(`weekly-newsletter: sent "${subject}" to ${to}`);
    return { sent: true, items: rows.length };
  },
});
