#!/usr/bin/env tsx
/**
 * tools/runs-from-fixtures.ts [--date YYYY-MM-DD] [--out ../../content/brainx/runs]
 *
 * Turns lib/fixtures/sample.ts into radar-run files (one per market, the
 * shape lib/radar/ingest-schema.ts expects) so the hand-researched,
 * URL-verified sample opportunities can be ingested as a real weekly run.
 * The research discipline was the same as the SOP's; this only re-shapes
 * the data. Pricing fields of 0 are dropped (the schema requires positive).
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { SAMPLE_OPPORTUNITIES } from '../lib/fixtures/sample'
import type { Vertical, EvidenceKind } from '../lib/radar/types'

const MARKET: Record<Vertical, string> = {
  real_estate: 'us-re-compliance',
  legal_compliance: 'legal-practice-growth',
  ai_fintech_regulation: 'ai-fintech-regulation',
}
const SOURCE_TYPE: Record<EvidenceKind, string> = {
  regulatory: 'regulator or legal publisher',
  demand: 'industry or trade publication',
  voice: 'consumer-facing forum or advice site',
  competitor: 'vendor or law-firm product page',
}

const args = process.argv.slice(2)
const date = args[args.indexOf('--date') + 1] && args.includes('--date') ? args[args.indexOf('--date') + 1]! : new Date().toISOString().slice(0, 10)
const out = args.includes('--out') ? args[args.indexOf('--out') + 1]! : join('..', '..', 'content', 'brainx', 'runs')
mkdirSync(out, { recursive: true })

const byMarket = new Map<string, typeof SAMPLE_OPPORTUNITIES[number][]>()
for (const o of SAMPLE_OPPORTUNITIES) {
  const slug = MARKET[o.vertical]
  byMarket.set(slug, [...(byMarket.get(slug) ?? []), o])
}

for (const [market_slug, ops] of byMarket) {
  const keyById = new Map<string, string>()
  const evidence = ops.flatMap((o) => o.evidence).map((e, i) => {
    const key = `ev-${String(i + 1).padStart(2, '0')}`
    keyById.set(e.id, key)
    return { key, kind: e.kind, title: e.title, url: e.url, publisher: e.publisher, published_at: e.published_at, excerpt: e.excerpt, source_type: SOURCE_TYPE[e.kind] }
  })
  const opportunities = ops.map((o) => {
    const pricing: Record<string, unknown> = {}
    if (o.proposed_pricing?.initial && o.proposed_pricing.initial > 0) pricing.initial = o.proposed_pricing.initial
    if (o.proposed_pricing?.recurring && o.proposed_pricing.recurring > 0) {
      pricing.recurring = o.proposed_pricing.recurring
      pricing.recurring_period = o.proposed_pricing.recurring_period ?? 'month'
    }
    return {
      slug: o.slug,
      name: o.name,
      problem: o.problem,
      target_customer: o.target_customer,
      proposed_product: o.proposed_product,
      proposed_pricing: Object.keys(pricing).length ? pricing : null,
      gtm_channels: [...o.gtm_channels],
      why_now: [...o.why_now],
      factor_scores: { ...o.factors },
      status_reason: o.status_reason,
      confidence: o.confidence,
      evidence: o.evidence.map((e) => ({ key: keyById.get(e.id)!, weight: e.weight, note: e.note })),
    }
  })
  const file = {
    run_date: date,
    market_slug,
    analyst_notes: `Radar run ${date}. Opportunities researched 2026-09-16 in a Claude Code session (model: Claude Fable 5.1 / Sonnet 5), every evidence URL opened and verified live (curl 200) before inclusion; same content as the public sample radar. Generated by tools/runs-from-fixtures.ts.`,
    evidence,
    opportunities,
  }
  const path = join(out, `${date}-${market_slug}.json`)
  writeFileSync(path, JSON.stringify(file, null, 2) + '\n')
  console.log(`${path}: ${opportunities.length} opportunities, ${evidence.length} evidence`)
}
