'use client'
import { useState, type CSSProperties } from 'react'
import Link from 'next/link'

const INPUT_STYLE: CSSProperties = {
  padding: '10px 14px',
  borderRadius: '8px',
  border: '1px solid var(--outline-var)',
  background: 'var(--bg)',
  color: 'var(--on-surface)',
  fontSize: 13,
  fontFamily: 'Manrope, sans-serif',
  width: '100%',
}

interface Obligation {
  obligation: string
  party: string
  deadline: string
  evidence_required: string
  source_provision: string
}

interface ExtractResult {
  summary: string
  obligations: Obligation[]
  legal_notice: string
  disclaimer_version: string
  generated_at: string
  extraction_id: string
}

export default function ObligationExtractor() {
  const [sourceText, setSourceText] = useState('')
  const [email, setEmail] = useState('')
  const [sourceUrl, setSourceUrl] = useState('')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [result, setResult] = useState<ExtractResult | null>(null)
  const [checked, setChecked] = useState<Record<number, boolean>>({})

  async function run() {
    const text = sourceText.trim()
    if (text.length < 40) {
      setError('Paste at least 40 characters of the regulation or contract text.')
      return
    }
    setBusy(true)
    setError('')
    setResult(null)
    try {
      const res = await fetch('/api/tools/obligation-extractor', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          source_text: text,
          email: email.trim() || undefined,
          source_url: sourceUrl.trim() || undefined,
        }),
      })
      const data = await res.json()
      if (!res.ok) {
        setError(data.error ?? 'Extraction is temporarily unavailable — please retry in a moment.')
        setBusy(false)
        return
      }
      setResult(data as ExtractResult)
      setChecked({})
    } catch {
      setError('Network issue — please retry.')
      setBusy(false)
    }
  }

  function exportJson() {
    if (!result) return
    const blob = new Blob([JSON.stringify(result, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `obligations-${new Date().toISOString().slice(0, 10)}.json`
    a.click()
    URL.revokeObjectURL(url)
  }

  function exportMarkdown() {
    if (!result) return
    const lines = [
      '# Compliance Obligations',
      '',
      result.summary,
      '',
      ...result.obligations.map((o, i) => [
        `## ${i + 1}. ${o.obligation}`,
        '',
        `- **Party:** ${o.party}`,
        `- **Deadline:** ${o.deadline}`,
        `- **Evidence required:** ${o.evidence_required}`,
        `- **Source provision:** ${o.source_provision}`,
        '',
      ].join('\n')),
      `---`,
      `*Generated by BizLegal AI Compliance Obligation Extractor (${result.disclaimer_version}). For discussion — verify against the source text.*`,
    ]
    const blob = new Blob([lines.join('\n')], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `obligations-${new Date().toISOString().slice(0, 10)}.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  const doneCount = Object.values(checked).filter(Boolean).length

  return (
    <div style={{ maxWidth: 860, margin: '0 auto', padding: '48px 32px' }}>
      <span className="section-label">Compliance · Regulation → obligation checklist · Free</span>
      <h1 style={{ marginBottom: 8, fontSize: 'clamp(28px,5vw,48px)' }}>Compliance Obligation Extractor</h1>
      <p style={{ color: 'var(--on-surface-var)', marginBottom: 8, lineHeight: 1.7 }}>
        Paste a regulation, contract, or compliance document — get a structured checklist of every obligation it
        imposes: <strong>who</strong> must do <strong>what</strong>, <strong>by when</strong>, and{' '}
        <strong>what evidence</strong> to keep — each tied to the exact provision it came from.
      </p>
      <p style={{ fontSize: 12, color: 'var(--outline)', lineHeight: 1.6, marginBottom: 32 }}>
        Extraction is <strong>for discussion — verify every obligation against the source text before acting</strong>.
        This is decision-support intelligence, not a legal opinion. Each obligation cites the verbatim provision it
        was extracted from; provisions that don&apos;t appear in your text are dropped automatically.
      </p>

      {error && (
        <div style={{ marginBottom: 20, padding: '14px 18px', borderRadius: '10px', background: '#fdecea', border: '1px solid #f5c6c0', color: '#c0392b', fontSize: 13, lineHeight: 1.6 }}>
          {error}
        </div>
      )}

      <div className="card" style={{ padding: '28px', background: 'var(--bg-mid)', marginBottom: 28 }}>
        <div style={{ marginBottom: 20 }}>
          <label style={{ display: 'block', fontSize: 12, fontWeight: 700, marginBottom: 6, color: 'var(--on-surface-var)' }}>
            Regulation / contract text
          </label>
          <textarea
            value={sourceText}
            onChange={(e) => setSourceText(e.target.value)}
            placeholder="Paste the regulation or contract text here (40–4000 characters)…"
            rows={8}
            style={{ ...INPUT_STYLE, resize: 'vertical', lineHeight: 1.6 }}
          />
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, marginBottom: 20 }}>
          <div>
            <label style={{ display: 'block', fontSize: 12, fontWeight: 700, marginBottom: 6, color: 'var(--on-surface-var)' }}>
              Source URL (optional)
            </label>
            <input
              type="url"
              value={sourceUrl}
              onChange={(e) => setSourceUrl(e.target.value)}
              placeholder="https://eur-lex.europa.eu/…"
              style={INPUT_STYLE}
            />
          </div>
          <div>
            <label style={{ display: 'block', fontSize: 12, fontWeight: 700, marginBottom: 6, color: 'var(--on-surface-var)' }}>
              Work email (optional)
            </label>
            <input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="you@company.com"
              style={INPUT_STYLE}
            />
          </div>
        </div>

        <button
          onClick={run}
          disabled={busy}
          style={{ padding: '12px 22px', borderRadius: 10, border: 'none', background: 'var(--primary)', color: '#fff', fontWeight: 700, cursor: 'pointer', fontSize: 14 }}
        >
          {busy ? 'Extracting obligations…' : 'Extract obligations'}
        </button>
        <p style={{ fontSize: 11, color: 'var(--outline)', marginTop: 14, lineHeight: 1.6 }}>
          Free — no account required. Email is optional and only used to follow up about the CASP compliance bundle.
          <Link href="/tools" style={{ color: 'var(--primary)' }}> ← Back to tools</Link>
        </p>
      </div>

      {result && (
        <div className="card" style={{ padding: '28px', background: 'var(--bg-mid)' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16, flexWrap: 'wrap', gap: 10 }}>
            <h2 style={{ fontSize: 18, fontWeight: 700, margin: 0 }}>
              {result.obligations.length} obligations extracted
              {doneCount > 0 && <span style={{ color: 'var(--on-surface-var)', fontWeight: 500 }}> · {doneCount} checked</span>}
            </h2>
            <div style={{ display: 'flex', gap: 8 }}>
              <button onClick={exportJson} style={{ padding: '8px 14px', borderRadius: 8, border: '1px solid var(--outline-var)', background: 'transparent', color: 'var(--on-surface)', cursor: 'pointer', fontSize: 12 }}>
                Export JSON
              </button>
              <button onClick={exportMarkdown} style={{ padding: '8px 14px', borderRadius: 8, border: '1px solid var(--outline-var)', background: 'transparent', color: 'var(--on-surface)', cursor: 'pointer', fontSize: 12 }}>
                Export Markdown
              </button>
            </div>
          </div>

          <p style={{ fontSize: 14, color: 'var(--on-surface-var)', lineHeight: 1.7, marginBottom: 24, padding: '14px 18px', background: 'var(--bg)', borderRadius: 10, border: '1px solid var(--outline-var)' }}>
            {result.summary}
          </p>

          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            {result.obligations.map((o, i) => (
              <div
                key={i}
                style={{
                  padding: '16px 18px',
                  borderRadius: 10,
                  background: 'var(--bg)',
                  border: checked[i] ? '1px solid var(--primary)' : '1px solid var(--outline-var)',
                }}
              >
                <label style={{ display: 'flex', gap: 10, alignItems: 'flex-start', cursor: 'pointer' }}>
                  <input
                    type="checkbox"
                    checked={!!checked[i]}
                    onChange={() => setChecked((c) => ({ ...c, [i]: !c[i] }))}
                    style={{ marginTop: 3 }}
                  />
                  <div style={{ flex: 1 }}>
                    <div style={{ fontSize: 14, fontWeight: 600, color: 'var(--on-surface)', lineHeight: 1.5, marginBottom: 6 }}>
                      {o.obligation}
                    </div>
                    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: 6, fontSize: 12, color: 'var(--on-surface-var)', lineHeight: 1.5 }}>
                      <div><strong>Party:</strong> {o.party}</div>
                      <div><strong>Deadline:</strong> {o.deadline}</div>
                      <div><strong>Evidence:</strong> {o.evidence_required}</div>
                    </div>
                    <div style={{ marginTop: 8, fontSize: 12, color: 'var(--outline)', lineHeight: 1.5 }}>
                      <strong>Source:</strong> <span style={{ fontFamily: 'monospace', fontSize: 11 }}>“{o.source_provision}”</span>
                    </div>
                  </div>
                </label>
              </div>
            ))}
          </div>

          <p style={{ fontSize: 11, color: 'var(--outline)', marginTop: 20, lineHeight: 1.6 }}>
            {result.legal_notice}
          </p>
        </div>
      )}
    </div>
  )
}
