import type { Guide } from './types'

export const GUIDE: Guide = {
  slug: 'compliance-software-opportunities-from-rule-changes',
  title: 'Compliance Software Opportunities Hiding in 2026 Rule Changes',
  description: 'Three live 2026 regulatory situations in real estate and fintech, and what each one implies for a compliance-software or advisory product — sourced to the regulators themselves.',
  publishedAt: '2026-09-16',
  paragraphs: [
    'A rule change is not automatically a product opportunity. Most rule changes get absorbed by existing compliance teams with a memo and a training session, and nothing new gets built. The situations worth watching are the ones with a specific shape: a hard, dated deadline; a buyer population that is identifiable and already spending on compliance; and either genuine confusion (a change that reversed or narrowed) or genuine urgency (a deadline that already passed and still has consequences). Three live 2026 situations fit that shape, in three different ways.',
    'The first is FinCEN’s Residential Real Estate Rule, and it is the clearest example of regulatory whiplash creating an opportunity rather than the rule itself creating one. The rule took effect March 1, 2026, requiring title companies, settlement agents, and closing attorneys to report certain non-financed residential transfers. Eighteen days later, on March 19, 2026, the U.S. District Court for the Eastern District of Texas vacated it nationwide, and FinCEN confirmed the next day that reporting persons are not currently required to file. FinCEN and the Department of Justice have appealed. The product opportunity here is not "help title companies comply with the rule" — that premise is currently false. It is "help title companies decide what to do with the reporting infrastructure they already built, while an appeal with no fixed timeline is pending, and while geographic targeting orders and state-level obligations that predate this rule are unaffected by the vacatur."',
    'The second is the GENIUS Act’s stablecoin licensing requirement, which is the opposite shape: a hard future deadline with moving rules underneath it. Beginning January 18, 2027, issuing a payment stablecoin in the United States without a federal or state license becomes unlawful. Three regulators are writing the rules an issuer must eventually satisfy on different clocks: the OCC proposed its rule on March 2, 2026, the FDIC Board approved its own proposal on April 7, 2026, and Treasury’s comment period on its own implementing rule for section 3 of the Act did not close until October 19, 2026 — inside the same calendar year the deadline year begins. An issuer building toward January 2027 is tracking three regulators’ drafts simultaneously with no single authoritative readiness checklist, which is a coordination gap, not an information gap.',
    'The third is MiCA’s transitional-period deadline in the European Union, and it is the most straightforward of the three: a deadline that has already passed, cleanly, with no extension mechanism. Every EU member state’s grandfathering window for crypto-asset service providers ended July 1, 2026. The European Securities and Markets Authority told national competent authorities directly that there is no extension mechanism and to treat late applications with caution. National authorities were still processing backlogged applications through the deadline — 41 firms were authorized in December 2025 alone, the single largest month on record, showing the last-minute pattern that repeated again around the July 2026 cutoff. The opportunity here is post-deadline: helping a firm caught without a license decide, market by market, which national authority has the shortest realistic path to authorization, versus an orderly wind-down.',
    'What the three situations share is not the regulation — real estate, payments, and crypto are unrelated markets — but the shape of the gap. In each case, the regulator’s own primary source is unambiguous about the current state of the rule, and the gap is not "what does the rule say" but "what should a specific, identifiable buyer do about it, right now, given everything else that is also true." A product built on the first framing goes stale the moment the rule changes again. A product built on the second framing survives the next change, because tracking the current state is the product.',
  ],
  citations: [
    { title: 'Residential Real Estate Frequently Asked Questions', url: 'https://www.fincen.gov/rre-faqs', publisher: 'FinCEN (U.S. Department of the Treasury)' },
    { title: 'FDIC Approves Proposal to Implement GENIUS Act Requirements and Standards', url: 'https://www.fdic.gov/news/press-releases/2026/fdic-approves-proposal-implement-genius-act-requirements-and-standards', publisher: 'Federal Deposit Insurance Corporation' },
    { title: 'GENIUS Act Regulations: Notice of Proposed Rulemaking', url: 'https://www.occ.gov/news-issuances/bulletins/2026/bulletin-2026-3.html', publisher: 'Office of the Comptroller of the Currency' },
    { title: 'Statement on the End of Transitional Periods under MiCA', url: 'https://www.esma.europa.eu/sites/default/files/2026-04/ESMA75-113276571-1679_Statement_on_the_end_of_transitional_periods_under_MiCA.pdf', publisher: 'European Securities and Markets Authority' },
  ],
  faqs: [
    { q: 'Is the FinCEN Residential Real Estate Rule back in force?', a: 'Not as of this writing. FinCEN’s own page states reporting persons are not currently required to file while the vacatur order remains in force, and that FinCEN and DOJ have appealed. Check FinCEN’s own page for the current status before acting.' },
    { q: 'When does the GENIUS Act licensing requirement actually start?', a: 'January 18, 2027, per the Act’s own effective-date structure reported across the 2026 rulemakings. A separate, later provision restricting unlicensed stablecoin sales to U.S. persons is set for July 18, 2028.' },
    { q: 'Can a CASP still get authorized in the EU after July 1, 2026?', a: 'Only by completing full MiCA authorization with a national competent authority — there is no grandfathering left. ESMA has told authorities to treat late applications with caution, and an unauthorized CASP must stop serving EU clients immediately.' },
    { q: 'Is any of this legal advice?', a: 'No. This guide summarizes public regulatory sources as of September 2026 for research purposes. Verify current status against the primary source before acting, and consult qualified counsel in the relevant jurisdiction.' },
  ],
  internalLinks: [
    { label: 'FinCEN whiplash opportunity on the sample radar', href: '/sample/fincen-real-estate-rule-vacatur-readiness' },
    { label: 'GENIUS Act readiness opportunity', href: '/sample/genius-act-stablecoin-issuer-readiness' },
    { label: 'MiCA post-deadline opportunity', href: '/sample/mica-transition-deadline-post-closure-entry' },
    { label: 'How to validate an idea with evidence', href: '/guides/validate-a-legal-tech-idea-with-evidence' },
    { label: 'Pricing', href: '/pricing' },
    { label: 'Disclaimer', href: '/disclaimer' },
  ],
}
