import type { Guide } from './types'

export const GUIDE: Guide = {
  slug: 'real-estate-compliance-product-signals',
  title: 'Real Estate Compliance Signals Worth Tracking After the NAR Settlement',
  description: 'What actually changed for brokerages after the 2024 NAR settlement, what changed again in January 2026, and which parts of the resulting confusion are a real product opportunity.',
  publishedAt: '2026-09-16',
  paragraphs: [
    'The National Association of REALTORS’ antitrust settlement produced two distinct waves of compliance change, more than a year apart, and treating them as one event is how a product ends up solving the wrong problem. The first wave landed on August 17, 2024: agents were required to sign a written buyer-broker agreement before touring homes, and offers of compensation to buyer’s agents could no longer be posted in the MLS. The second wave landed January 1, 2026, when NAR amended Article 7 of its Code of Ethics to narrow the disclosure requirement — a broker now has to disclose buyer-agreement compensation terms only to their own client, not to all parties in the transaction. These are related but separate changes, and a brokerage’s 2024-era training materials do not automatically cover the 2026 amendment.',
    'The practical confusion this produced is well documented from the consumer side, not just the industry side. Advice content aimed directly at buyers and sellers — "Do I really have to pay a 2.5% buyer’s agent fee?" and "My agent wants me to sign a commission agreement before listing — do I have to?" — exists because people are still asking these questions in 2026, more than a year after the underlying settlement took effect. California’s own Department of Real Estate issued a consumer alert on the practice changes, which is a signal that the confusion reached a state regulator’s desk, not just brokerage compliance departments.',
    'Litigation status adds a layer that a product built on this space needs to track separately from the practice changes themselves. The Eighth Circuit heard arguments on the settlement agreement on January 14, 2026, with a decision expected later in 2026. Whatever that panel decides, it does not roll back the practice changes already in effect nationwide — the written buyer-agreement requirement and the MLS compensation-posting ban are settlement terms, not a court order that the appeal directly threatens. A product that implies the appeal could reverse the practice changes would be overstating the litigation’s actual scope.',
    'Where this becomes a real opportunity, rather than a curiosity, is at the brokerage compliance layer specifically — not the individual-agent layer, where NAR, state associations, and countless YouTube explainers have already saturated the space with free content. A multi-office brokerage or franchise needs its buyer-agreement disclosure scripts, staff training materials, and compliance changelog to reflect the January 2026 Article 7 amendment specifically, in language its own broker-of-record can hand to every agent without rewriting it. That is a narrower, more defensible target than "explain the NAR settlement to real estate agents," which is already a crowded, mostly free category.',
    'The honest read on urgency: this is a watch-tier opportunity, not a build-tier one, absent a specific signal that a brokerage or franchise has asked for it. The underlying settlement is 19-plus months old, most of the acute confusion has already been addressed by the flood of 2024-era content, and the January 2026 amendment is a narrowing, technical change rather than a new practice shock. The right move is to track for a specific buyer — a franchise compliance department, a state association — publicly asking for updated materials, rather than building the refresh kit speculatively and hoping demand catches up.',
    'Worth separating clearly, because the two get conflated in casual coverage: the NAR settlement is a private antitrust settlement changing brokerage commission practices, while a separate, unrelated federal rule (FinCEN’s Residential Real Estate Rule) governs anti-money-laundering reporting for certain non-financed residential transfers and was itself vacated by a federal court in March 2026. A brokerage compliance product built around "real estate rule changes" without distinguishing which regulator, which mechanism, and which specific practice is affected will mislead the very buyers it is trying to help. The companion guide on 2026 rule changes below walks through the FinCEN situation in the same evidence-first format this guide uses for the NAR settlement.',
  ],
  citations: [
    { title: '2026 Summary of Key Professional Standards Changes', url: 'https://www.nar.realtor/about-nar/policies/2026-summary-of-key-professional-standards-changes', publisher: 'National Association of REALTORS®' },
    { title: 'Consumer Alert: Changes to Real Estate Representation', url: 'https://www.dre.ca.gov/consumers/consumeralerts/ConsumerAlert_20241114_Changes_to_Real_Estate_Representation.html', publisher: 'California Department of Real Estate' },
    { title: 'Fact Sheet for FinCEN Geographic Targeting Orders', url: 'https://www.alta.org/media/pdf/fincen/fact-sheet-fincen-gto.pdf', publisher: 'American Land Title Association' },
  ],
  faqs: [
    { q: 'What exactly changed on January 1, 2026?', a: 'NAR amended Article 7 of its Code of Ethics to require disclosure of buyer-broker compensation terms only to the REALTOR’s own client, not to all parties in the transaction — narrower than the disclosure practice many brokerages adopted after the original August 2024 settlement.' },
    { q: 'Does the pending Eighth Circuit appeal undo the practice changes?', a: 'No. The practice changes — mandatory written buyer-broker agreements and the end of MLS compensation posting — are already in effect nationwide regardless of the appeal’s outcome, based on current reporting as of this guide’s publication date.' },
    { q: 'Is this the same issue as the FinCEN real estate rule?', a: 'No — different regulator, different mechanism. FinCEN’s rule is a federal AML reporting requirement for certain non-financed residential transfers; the NAR settlement is a private antitrust settlement changing brokerage commission practices. See the companion guide on 2026 rule changes for the FinCEN situation.' },
    { q: 'Is this legal advice for my brokerage?', a: 'No, this is not legal advice — it is a summary of public sources for research purposes. Confirm current requirements with NAR, your state association, and consult qualified counsel before updating compliance materials.' },
  ],
  internalLinks: [
    { label: 'NAR Article 7 opportunity on the sample radar', href: '/sample/nar-article-7-disclosure-refresh' },
    { label: 'FinCEN whiplash opportunity', href: '/sample/fincen-real-estate-rule-vacatur-readiness' },
    { label: 'Compliance software opportunities in 2026 rule changes', href: '/guides/compliance-software-opportunities-from-rule-changes' },
    { label: 'How to validate an idea with evidence', href: '/guides/validate-a-legal-tech-idea-with-evidence' },
    { label: 'Pricing', href: '/pricing' },
    { label: 'Disclaimer', href: '/disclaimer' },
  ],
}
