import Link from 'next/link'

export const metadata = {
  title: 'Terms of Service | TRACR — Powered by BizLegal AI',
  description: 'Terms of service for TRACR blockchain forensic intelligence platform by BizLegal AI (bizlegal-ai.com).',
}

const s = { minHeight: '100vh', background: '#0b1326', color: '#dae2fd', fontFamily: "'DM Sans', sans-serif", padding: '80px 32px' } as const
const inner = { maxWidth: '720px', margin: '0 auto' } as const
const h1 = { fontSize: '36px', fontWeight: 800, marginBottom: '8px', color: '#f0f2ff' } as const
const meta = { fontSize: '12px', color: '#636680', marginBottom: '40px' } as const
const h2 = { fontSize: '18px', fontWeight: 600, color: '#f0f2ff', marginBottom: '10px', marginTop: '32px' } as const
const p = { fontSize: '14px', color: '#94a3b8', lineHeight: 1.8, marginBottom: '20px' } as const
const a = { color: '#a5b4fc', textDecoration: 'none' } as const

export default function TermsPage() {
  return (
    <div style={s}><div style={inner}>
      <h1 style={h1}>Terms of Service</h1>
      <p style={{ fontSize: '13px', color: '#a5b4fc', marginBottom: '4px' }}>TRACR — Powered by <a href="https://bizlegal-ai.com" style={a}>BizLegal AI</a> (bizlegal-ai.com)</p>
      <p style={meta}>Last updated: April 2026</p>
      <h2 style={h2}>1. Service Description</h2>
      <p style={p}>TRACR is a regulatory risk intelligence platform operated by BizLegal AI. We provide AI-powered compliance scanning across EU (MiCA), GDPR, SEC, and VARA frameworks. TRACR is not a law firm and does not provide legal advice.</p>
      <h2 style={h2}>2. No Legal Advice</h2>
      <p style={p}>All reports, analyses, and scores generated by TRACR are for informational purposes only. They do not constitute legal advice. Consult a licensed attorney before relying on any report.</p>
      <h2 style={h2}>3. AI-Generated Content</h2>
      <p style={p}>Reports are generated using artificial intelligence (Anthropic Claude). While we strive for accuracy, AI-generated content may contain errors or omissions. Always verify critical findings independently.</p>
      <h2 style={h2}>4. Payment Terms</h2>
      <p style={p}>Payment is required before full report generation. We accept cryptocurrency via NOWPayments and card payments via Payoneer. See our Refund Policy for cancellation terms.</p>
      <h2 style={h2}>5. Limitation of Liability</h2>
      <p style={p}>TRACR and BizLegal AI shall not be liable for any damages arising from use of the Service, including regulatory penalties, legal costs, or financial losses. Reports are provided &quot;as is&quot; without warranty.</p>
      <h2 style={h2}>6. Governing Law</h2>
      <p style={p}>These Terms are governed by the laws of the State of Delaware, United States.</p>
      <h2 style={h2}>7. Contact</h2>
      <p style={p}>Questions: <a href="mailto:team@bizlegal-ai.com" style={a}>team@bizlegal-ai.com</a></p>
      <div style={{ borderTop: '1px solid #1e293b', marginTop: '40px', paddingTop: '20px', display: 'flex', gap: '24px' }}>
        <Link href="/privacy" style={a}>← Privacy Policy</Link>
        <Link href="/disclaimer" style={a}>Disclaimer →</Link>
      </div>
    </div></div>
  )
}
