-- 20260607 — Gap-page visual enrichment columns
--
-- Adds visual-asset columns to public.gap_pages so the forge gap-page
-- renderer can show an editorial hero image + a Mermaid compliance-flow
-- diagram alongside the existing structured text fields. Pure additive
-- migration: all columns are nullable and default NULL, so existing rows
-- and the current renderer keep working unchanged until visuals are
-- generated by scripts/generate-gap-visuals.mjs.
--
-- NOT APPLIED AUTOMATICALLY. Apply via the Supabase dashboard SQL editor
-- (project ydghhcuuopqzgqcicubg) or the Supabase MCP `apply_migration`.
-- The repo pre-commit hook does not run migrations.
--
--   hero_image_url   — public URL of the generated hero PNG in the
--                      `gap-visuals` Storage bucket.
--   diagram_mermaid  — raw Mermaid source (flowchart/graph) summarizing
--                      the compliance decision/flow. Rendered client-side.
--   diagram_caption  — short human-readable caption shown under the
--                      diagram (figure caption / accessible description).

begin;

alter table public.gap_pages
  add column if not exists hero_image_url  text,
  add column if not exists diagram_mermaid text,
  add column if not exists diagram_caption text;

comment on column public.gap_pages.hero_image_url  is 'Public URL of generated editorial hero image (gap-visuals bucket).';
comment on column public.gap_pages.diagram_mermaid is 'Raw Mermaid source summarizing the compliance decision/flow.';
comment on column public.gap_pages.diagram_caption is 'Caption / accessible description shown under the rendered diagram.';

commit;
