#!/usr/bin/env python3
"""partner_onboarding.py - OCI Deal Router partner onboarding."""
import os, sys, json, urllib.request, urllib.error
from datetime import datetime, timezone
from pathlib import Path

VAULT_PATH = Path('/opt/bizlegal/curator/.env')
SUPABASE_URL = os.getenv('SUPABASE_URL', 'https://ydghhcuuopqzgqcicubg.supabase.co')
SUPABASE_KEY = os.getenv('SUPABASE_SECRET', os.getenv('SUPABASE_SERVICE_KEY', ''))
REPORTS_DIR = Path('/opt/bizlegal/decisions')

PARTNER_TARGETS = [
    {'jurisdiction': 'UAE (DIFC)', 'city': 'Dubai', 'specialty': 'crypto regulation, VASP licensing', 'target_count': 5, 'fee_pct': 8, 'avg_deal_usd': 5000, 'linkedin_search': '"DIFC" AND "crypto" AND "lawyer"'},
    {'jurisdiction': 'Singapore', 'city': 'Singapore', 'specialty': 'family office, MAS PSA licensing', 'target_count': 5, 'fee_pct': 8, 'avg_deal_usd': 8000, 'linkedin_search': '"Singapore" AND "PSA" AND "compliance"'},
    {'jurisdiction': 'US (NY/CA)', 'city': 'New York / San Francisco', 'specialty': 'SEC enforcement defense, Reg D structuring', 'target_count': 8, 'fee_pct': 10, 'avg_deal_usd': 15000, 'linkedin_search': '"SEC" AND "crypto" AND "lawyer" AND ("NY" OR "CA")'},
    {'jurisdiction': 'UK', 'city': 'London', 'specialty': 'FCA compliance, crypto advisory', 'target_count': 4, 'fee_pct': 8, 'avg_deal_usd': 6000, 'linkedin_search': '"FCA" AND "crypto" AND "compliance" AND "UK"'},
]

DM_TEMPLATES = {
    'UAE (DIFC)': 'Hi {first_name},\n\nI saw your work on {recent_topic}. I am building OCI - a deal router that connects VASP/crypto founders in the UAE with the right regulatory counsel. We pay 8% referral fee on close (avg deal $5K).\n\nLooking for 1-2 DIFC-licensed partners who want inbound crypto clients without the BD overhead. Reply if interested and I will send the 1-pager.',
    'Singapore': 'Hi {first_name},\n\nFollowing your PSA licensing work. I run OCI Deal Router - we send qualified crypto founders to specialist lawyers in SG. 8% rev share, avg deal $8K, you only get pre-qualified leads.\n\nWould you be open to a 15-min call this week?',
    'US (NY/CA)': 'Hi {first_name},\n\nReading your recent SEC commentary. OCI Deal Router - we route pre-vetted crypto founders to specialist counsel. 10% rev share on close, avg deal $15K, no retainer, just leads.\n\nWorth a 15-min intro?',
    'UK': 'Hi {first_name},\n\nFollowing your FCA compliance practice. I run OCI - crypto founders get matched to specialist UK counsel. 8% rev share, avg deal $6K. We send leads, you close them.\n\nOpen to a brief intro call?',
}

PARTNER_TABLE_SQL = '''-- Create the partners table if not exists
CREATE TABLE IF NOT EXISTS deal_router_partners (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    jurisdiction TEXT NOT NULL,
    city TEXT,
    specialty TEXT,
    fee_pct NUMERIC(5,2) DEFAULT 8.0,
    email TEXT UNIQUE,
    linkedin TEXT,
    status TEXT DEFAULT 'pending',
    total_deals INTEGER DEFAULT 0,
    total_revenue_usd NUMERIC(12,2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_contact_at TIMESTAMPTZ,
    notes TEXT
);
'''

PARTNER_SQL_TEMPLATE = '''-- Insert OCI partner
INSERT INTO deal_router_partners (name, jurisdiction, city, specialty, fee_pct, email, linkedin, status, created_at, notes)
VALUES ('{name}', '{jurisdiction}', '{city}', '{specialty}', {fee_pct}, '{email}', '{linkedin}', 'pending', NOW(), 'avg_deal_usd={avg_deal_usd}, source=outreach-{date}')
ON CONFLICT (email) DO UPDATE SET status = 'pending', notes = EXCLUDED.notes;
'''


def main():
    global SUPABASE_KEY
    if not SUPABASE_KEY and VAULT_PATH.exists():
        for line in VAULT_PATH.read_text().splitlines():
            if '=' in line and not line.startswith('#'):
                k, v = line.split('=', 1)
                os.environ.setdefault(k.strip(), v.strip())
        SUPABASE_KEY = os.getenv('SUPABASE_SECRET', os.getenv('SUPABASE_SERVICE_KEY', ''))

    today = datetime.now(timezone.utc).strftime('%Y-%m-%d')
    print(f'[{today}] partner_onboarding: generating outreach plan')

    md = f'# OCI Partner Outreach Plan -- {today}\n\n'
    md += 'Generated by partner_onboarding.py\n\n'
    md += '## Quarterly Targets\n\n'
    md += '| Jurisdiction | Targets | Fee | Avg Deal | Mo Revenue (1 close) | Mo Revenue (5 closes) |\n|---|---|---|---|---|---|\n'
    for t in PARTNER_TARGETS:
        per_close = t['avg_deal_usd'] * t['fee_pct'] / 100
        md += f"| {t['jurisdiction']} | {t['target_count']} | {t['fee_pct']}% | ${t['avg_deal_usd']:,} | ${per_close:,.0f} | ${per_close*5:,.0f} |\n"

    md += '\n## SQL: Create Partners Table (run once)\n\n```sql\n' + PARTNER_TABLE_SQL + '```\n\n'
    md += '## SQL: Insert New Partner Template\n\n```sql\n' + PARTNER_SQL_TEMPLATE + '```\n\n'
    md += '## LinkedIn DM Scripts\n\n'
    for jur, tmpl in DM_TEMPLATES.items():
        md += f'### {jur}\n```\n{tmpl}\n```\n\n'

    md += '## LinkedIn Search Queries\n\n'
    for t in PARTNER_TARGETS:
        md += f"- **{t['jurisdiction']}**: `{t['linkedin_search']}`\n"

    md += '\n## Action Plan This Week\n\n'
    md += '1. Run the SQL above in Supabase SQL editor (create table first time only)\n'
    md += '2. Search LinkedIn for each jurisdiction using the queries above\n'
    md += '3. Send DMs using the templates (replace `{first_name}` and `{recent_topic}`)\n'
    md += '4. When partner replies positively, send 1-pager:\n\n'
    md += '> **OCI Deal Router -- Partner Program**\n>\n'
    md += '> We connect you with pre-qualified founders in [crypto/web3/fintech] who need your compliance expertise.\n>\n'
    md += '> **How it works:**\n'
    md += '> 1. Founders submit a brief via router.bizlegal-ai.com\n'
    md += '> 2. Our agent classifies by jurisdiction + specialty\n'
    md += '> 3. We send you the matched leads with full context\n'
    md += '> 4. You take them to close; we pay 8% on close\n\n'
    md += '> **Avg deal:** $5-15K. **Payout:** 30 days after invoice. **Volume:** 5-20 leads/mo per partner.\n'
    md += '5. Track replies in `deal_router_partners` table (status: pending -> active)\n'
    md += '6. Once 5 partners active, expect $2-5K/mo in referral fees\n'

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    out = REPORTS_DIR / f'partner-outreach-{today}.md'
    out.write_text(md)

    try:
        req = urllib.request.Request(
            SUPABASE_URL + '/rest/v1/agent_runs',
            data=json.dumps([{
                'agent_name': 'partner_onboarding',
                'workflow_id': 'oci-deal-router',
                'action': 'generate_outreach_plan',
                'status': 'success',
                'details': {
                    'jurisdictions': len(PARTNER_TARGETS),
                    'total_targets': sum(t['target_count'] for t in PARTNER_TARGETS),
                },
            }]).encode(),
            headers={'apikey': SUPABASE_KEY, 'Authorization': 'Bearer ' + SUPABASE_KEY, 'Content-Type': 'application/json', 'Prefer': 'return=minimal'},
            method='POST',
        )
        urllib.request.urlopen(req, timeout=15)
    except Exception as e:
        print(f'  [supabase log] {e}')

    print(f'  report: {out}')


if __name__ == '__main__':
    main()
