import { NextResponse } from 'next/server'
import Anthropic from '@anthropic-ai/sdk'

export const maxDuration = 60

const client = new Anthropic()

export interface BlockchainReportRequest {
  projectName: string
  tokenName: string
  tokenSymbol: string
  chain: string
  tokenType: 'utility' | 'security' | 'payment' | 'governance' | 'nft' | 'stablecoin' | 'unknown'
  projectDescription: string
  targetJurisdictions: string[]
  hasPublicSale: boolean
  hasDeFi: boolean
  hasStaking: boolean
  email?: string
  tier: 'preview' | 'full'
}

export interface JurisdictionAnalysis {
  jurisdiction: string
  flag: string
  regulator: string
  status: 'compliant' | 'partial' | 'non_compliant' | 'prohibited' | 'unclear'
  statusLabel: string
  tokenClassification: string
  requiredLicenses: string[]
  riskFlags: Array<{ flag: string; severity: 'low' | 'medium' | 'high' | 'critical' }>
  keyActions: string[]
  estimatedTimeline: string
  estimatedCost: string
}

export interface BlockchainReport {
  projectName: string
  tokenName: string
  generatedAt: string
  overallRiskScore: number
  overallRiskLevel: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'
  executiveSummary: string
  howeyTestAnalysis: {
    investmentOfMoney: boolean
    commonEnterprise: boolean
    expectationOfProfits: boolean
    effortsOfOthers: boolean
    verdict: 'LIKELY_SECURITY' | 'LIKELY_NOT_SECURITY' | 'UNCERTAIN'
    reasoning: string
  }
  jurisdictions: JurisdictionAnalysis[]
  criticalRisks: Array<{ risk: string; jurisdiction: string; action: string }>
  topRecommendations: string[]
  estimatedTotalCost: string
  nextSteps: string[]
  disclaimer: string
}

export async function POST(req: Request) {
  try {
    const body: BlockchainReportRequest = await req.json()

    const {
      projectName, tokenName, tokenSymbol, chain, tokenType,
      projectDescription, targetJurisdictions, hasPublicSale,
      hasDeFi, hasStaking, tier
    } = body

    if (!projectName || !tokenName || !projectDescription) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 })
    }

    const jurisdictionList = targetJurisdictions.length > 0
      ? targetJurisdictions
      : ['UAE (VARA)', 'European Union (MiCA)', 'United States (SEC/CFTC)', 'United Kingdom (FCA)', 'Singapore (MAS)', 'Canada (CSA)']

    const isPreview = tier === 'preview'
    const jurisdictionsToAnalyze = isPreview ? jurisdictionList.slice(0, 2) : jurisdictionList

    const prompt = `You are a tier-1 blockchain regulatory attorney with expertise in global crypto compliance. Generate a comprehensive regulatory compliance report for the following blockchain project.

PROJECT DETAILS:
- Project Name: ${projectName}
- Token Name: ${tokenName} (${tokenSymbol})
- Blockchain: ${chain}
- Token Type: ${tokenType}
- Description: ${projectDescription}
- Public Token Sale: ${hasPublicSale ? 'Yes' : 'No'}
- DeFi Features: ${hasDeFi ? 'Yes' : 'No'}
- Staking/Yield: ${hasStaking ? 'Yes' : 'No'}
- Target Jurisdictions: ${jurisdictionsToAnalyze.join(', ')}

Generate a detailed compliance report in the following JSON format. Be specific, actionable, and accurate based on current regulations (2024-2025).

{
  "overallRiskScore": <number 0-100>,
  "overallRiskLevel": "<LOW|MEDIUM|HIGH|CRITICAL>",
  "executiveSummary": "<2-3 sentence executive summary>",
  "howeyTestAnalysis": {
    "investmentOfMoney": <true|false>,
    "commonEnterprise": <true|false>,
    "expectationOfProfits": <true|false>,
    "effortsOfOthers": <true|false>,
    "verdict": "<LIKELY_SECURITY|LIKELY_NOT_SECURITY|UNCERTAIN>",
    "reasoning": "<2-3 sentence Howey Test analysis>"
  },
  "jurisdictions": [
    {
      "jurisdiction": "<full jurisdiction name>",
      "flag": "<emoji flag>",
      "regulator": "<regulator name>",
      "status": "<compliant|partial|non_compliant|prohibited|unclear>",
      "statusLabel": "<human readable status>",
      "tokenClassification": "<how regulator classifies this token>",
      "requiredLicenses": ["<license 1>", "<license 2>"],
      "riskFlags": [
        {"flag": "<risk description>", "severity": "<low|medium|high|critical>"}
      ],
      "keyActions": ["<action 1>", "<action 2>", "<action 3>"],
      "estimatedTimeline": "<e.g., 6-12 months>",
      "estimatedCost": "<e.g., $50,000-$150,000>"
    }
  ],
  "criticalRisks": [
    {"risk": "<risk>", "jurisdiction": "<jurisdiction>", "action": "<immediate action>"}
  ],
  "topRecommendations": ["<recommendation 1>", "<recommendation 2>", "<recommendation 3>", "<recommendation 4>", "<recommendation 5>"],
  "estimatedTotalCost": "<total legal cost range to achieve compliance>",
  "nextSteps": ["<step 1>", "<step 2>", "<step 3>"],
  "disclaimer": "This report is generated by AI for informational purposes only and does not constitute legal advice. Consult qualified legal counsel before making compliance decisions."
}

Be thorough, jurisdiction-specific, and revenue-focused. Flag all material risks. Include specific regulation names (e.g., VARA 2023, MiCA Article 3, SEC Howey Test, FCA PS19/22).`

    const message = await client.messages.create({
      model: 'claude-sonnet-4-6',
      max_tokens: isPreview ? 2000 : 4000,
      messages: [{ role: 'user', content: prompt }],
    })

    const content = message.content[0]
    if (content.type !== 'text') {
      throw new Error('Unexpected response type')
    }

    // Extract JSON from response
    const jsonMatch = content.text.match(/\{[\s\S]*\}/)
    if (!jsonMatch) throw new Error('No JSON in response')

    const reportData = JSON.parse(jsonMatch[0])

    const report: BlockchainReport = {
      projectName,
      tokenName,
      generatedAt: new Date().toISOString(),
      overallRiskScore: reportData.overallRiskScore,
      overallRiskLevel: reportData.overallRiskLevel,
      executiveSummary: reportData.executiveSummary,
      howeyTestAnalysis: reportData.howeyTestAnalysis,
      jurisdictions: reportData.jurisdictions || [],
      criticalRisks: reportData.criticalRisks || [],
      topRecommendations: reportData.topRecommendations || [],
      estimatedTotalCost: reportData.estimatedTotalCost,
      nextSteps: reportData.nextSteps || [],
      disclaimer: reportData.disclaimer,
    }

    return NextResponse.json({ report, tier })

  } catch (err) {
    console.error('Blockchain report error:', err)
    return NextResponse.json({ error: 'Report generation failed. Please try again.' }, { status: 500 })
  }
}
