import type { KbItem } from '../ai-act/knowledge-base'

export const IMMIGRATION_KB: KbItem[] = [
  {
    id: 'ina-h1b',
    source_name: 'INA § 101(a)(15)(H)(i)(b) — H-1B Specialty Occupation',
    source_url: 'https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title8-section1101&num=0',
    jurisdiction: 'US',
    topics: ['h-1b', 'specialty-occupation', 'nonimmigrant'],
    text: 'An alien coming temporarily to perform services in a specialty occupation requiring theoretical and practical application of a body of highly specialized knowledge, and attainment of a bachelor\'s or higher degree in the specific specialty as a minimum qualification. Requires Labor Condition Application (LCA) approved by DOL. Annual cap: 65,000 + 20,000 master\'s exemption.',
  },
  {
    id: 'ina-l1',
    source_name: 'INA § 101(a)(15)(L) — L-1 Intracompany Transferee',
    source_url: 'https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title8-section1101&num=0',
    jurisdiction: 'US',
    topics: ['l-1', 'intracompany', 'nonimmigrant', 'multinational'],
    text: 'L-1A: Managers/executives transferred from qualifying foreign office. L-1B: Specialized knowledge workers. Requires 1 year of continuous employment abroad in the preceding 3 years. No annual cap. Initial stay: L-1A 3 years (new office: 1 year), max 7 years. L-1B max 5 years.',
  },
  {
    id: 'ina-o1',
    source_name: 'INA § 101(a)(15)(O) — O-1 Extraordinary Ability',
    source_url: 'https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title8-section1101&num=0',
    jurisdiction: 'US',
    topics: ['o-1', 'extraordinary-ability', 'nonimmigrant'],
    text: 'O-1A: Extraordinary ability in sciences, education, business, or athletics demonstrated by sustained national or international acclaim. O-1B: Extraordinary achievement in arts or motion picture/TV. Must meet ≥3 of 8 evidentiary criteria (awards, publications, judging, original contributions, etc.) or show comparable evidence. No annual cap.',
  },
  {
    id: 'ina-eb1',
    source_name: 'INA § 203(b)(1) — EB-1 Priority Workers',
    source_url: 'https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title8-section1203&num=0',
    jurisdiction: 'US',
    topics: ['eb-1', 'immigrant', 'green-card', 'priority-worker'],
    text: 'EB-1A: Extraordinary ability (same 10 criteria as O-1A, meet ≥3). No labor certification or job offer needed. EB-1B: Outstanding professors/researchers with 3+ years research experience. EB-1C: Multinational managers/executives (1 year abroad in preceding 3 years). Annual allocation: ~40,000 visas.',
  },
  {
    id: 'ina-eb2',
    source_name: 'INA § 203(b)(2) — EB-2 Advanced Degree / NIW',
    source_url: 'https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title8-section1203&num=0',
    jurisdiction: 'US',
    topics: ['eb-2', 'niw', 'immigrant', 'green-card', 'advanced-degree'],
    text: 'EB-2: Professionals with advanced degree (master\'s+) or exceptional ability. Normally requires PERM labor certification. EB-2 NIW (National Interest Waiver): waives labor certification if the work is in the national interest. Three-prong test (Matter of Dhanasar): (1) substantial merit and national importance, (2) well-positioned to advance, (3) beneficial to waive requirements.',
  },
  {
    id: 'ina-eb5',
    source_name: 'INA § 203(b)(5) — EB-5 Immigrant Investor',
    source_url: 'https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title8-section1203&num=0',
    jurisdiction: 'US',
    topics: ['eb-5', 'investor', 'immigrant', 'green-card'],
    text: 'EB-5 requires capital investment of $1.05M ($800,000 in TEA) creating 10+ full-time jobs. Conditional green card for 2 years, then removal of conditions. Regional Center program allows indirect job creation. Annual allocation: ~10,000 visas.',
  },
  {
    id: 'cfr-h1b-lca',
    source_name: '8 CFR § 214.2(h) — H-1B LCA Requirements',
    source_url: 'https://www.ecfr.gov/current/title-8/chapter-I/subchapter-B/part-214/subpart-A/section-214.2',
    jurisdiction: 'US',
    topics: ['h-1b', 'lca', 'prevailing-wage', 'dol'],
    text: 'Labor Condition Application (LCA) requirements: (1) Pay at least the prevailing wage or actual wage, whichever is higher, (2) Working conditions will not adversely affect other similarly employed workers, (3) No strike/lockout at place of employment, (4) Notice to union or employees. LCA must be filed on Form 9035/9035E with DOL.',
  },
  {
    id: 'uscis-i129',
    source_name: 'USCIS Form I-129 — Petition for Nonimmigrant Worker',
    source_url: 'https://www.uscis.gov/i-129',
    jurisdiction: 'US',
    topics: ['i-129', 'h-1b', 'l-1', 'o-1', 'form'],
    text: 'Form I-129 is used by employers to petition for nonimmigrant workers (H-1B, L-1, O-1, etc.). Filing fee: $460 base + $500 fraud prevention fee (H-1B/L-1) + $750/$1,500 ACWIA fee (H-1B, based on employer size) + optional $2,805 premium processing. Processing: standard 3-8 months, premium 15 business days.',
  },
  {
    id: 'uscis-i140',
    source_name: 'USCIS Form I-140 — Immigrant Petition for Alien Workers',
    source_url: 'https://www.uscis.gov/i-140',
    jurisdiction: 'US',
    topics: ['i-140', 'eb-1', 'eb-2', 'eb-3', 'green-card', 'form'],
    text: 'Form I-140 is filed by employers (or self-petition for EB-1A/NIW) for immigrant worker classification. Filing fee: $700. Premium processing available ($2,805, 45 calendar days). Approved I-140 establishes priority date for visa availability. Beneficiary must wait for visa number if backlogged.',
  },
  {
    id: 'uscis-asylum',
    source_name: 'INA § 208 — Asylum',
    source_url: 'https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title8-section1158&num=0',
    jurisdiction: 'US',
    topics: ['asylum', 'refugee', 'humanitarian'],
    text: 'Asylum may be granted to an alien physically present in the US who demonstrates past persecution or well-founded fear of future persecution on account of race, religion, nationality, membership in a particular social group, or political opinion. Must file Form I-589 within 1 year of arrival (exceptions exist). Affirmative process (USCIS) or defensive process (immigration court).',
  },
]
