"""CoGuard Court Binder Generator — FastAPI on port 8083.

Accepts POST /generate (x-internal-secret gated), fetches messages from
Supabase, applies Bates numbering, generates a ReportLab PDF with:
  - Page 1: Chain-of-custody certificate
  - Page 2: Incident index (flagged / high-conflict messages)
  - Pages 3+: Full chronological message log

Uploads to Supabase Storage, updates coguard_binders.status → 'ready',
fires email notification to subscriber.

Systemd unit: coguard-binder.service (port 8083)
"""
from __future__ import annotations

import hashlib
import hmac as hmac_lib
import io
import json
import logging
import os
from datetime import datetime, timezone

import httpx
import uvicorn
from fastapi import FastAPI, Header, HTTPException, Request
from fastapi.responses import JSONResponse
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.lib import colors

logger = logging.getLogger(__name__)

SUPABASE_URL = os.environ.get("SUPABASE_URL", "")
SUPABASE_SERVICE_KEY = os.environ.get("SUPABASE_SERVICE_KEY", os.environ.get("SUPABASE_SECRET", ""))
RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "")
RESEND_FROM = os.environ.get("RESEND_FROM", "noreply@coguard.bizlegal-ai.com")
INTERNAL_SECRET = os.environ.get("COGUARD_INTERNAL_SECRET", "")

app = FastAPI(title="coguard-binder", version="0.1.0")


def _supabase_headers() -> dict[str, str]:
    return {"apikey": SUPABASE_SERVICE_KEY, "Authorization": f"Bearer {SUPABASE_SERVICE_KEY}", "Content-Type": "application/json", "Prefer": "return=representation"}


def _verify_secret(provided: str | None) -> None:
    if not INTERNAL_SECRET:
        raise HTTPException(status_code=500, detail="internal secret not configured")
    if provided != INTERNAL_SECRET:
        raise HTTPException(status_code=401, detail="unauthorized")


def _bates_label(start: int, offset: int) -> str:
    return f"BL-{str(start + offset).zfill(7)}"


def _build_pdf(
    subscriber_id: str,
    binder_id: str,
    date_from: str,
    date_to: str,
    messages: list[dict],
    bates_start: int,
) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=letter, rightMargin=inch, leftMargin=inch, topMargin=inch, bottomMargin=inch)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("Title2", parent=styles["Title"], fontSize=18, spaceAfter=12)
    h2_style = ParagraphStyle("H2", parent=styles["Heading2"], fontSize=13, spaceAfter=8)
    body_style = ParagraphStyle("Body2", parent=styles["Normal"], fontSize=9, leading=13, spaceAfter=4)
    mono_style = ParagraphStyle("Mono", parent=styles["Normal"], fontName="Courier", fontSize=7, textColor=colors.grey, leading=10)
    flag_style = ParagraphStyle("Flag", parent=styles["Normal"], fontSize=8, textColor=colors.darkred)

    story = []

    # ── Page 1: Chain-of-custody certificate ──────────────────────────────────
    story.append(Paragraph("CoGuard Communication Log", title_style))
    story.append(Paragraph("Chain-of-Custody Certificate", h2_style))
    story.append(Spacer(1, 0.1 * inch))

    cert_data = [
        ["Binder ID", binder_id],
        ["Subscriber ID", subscriber_id],
        ["Date Range", f"{date_from[:10]} – {date_to[:10]}"],
        ["Message Count", str(len(messages))],
        ["Bates Range", f"BL-{str(bates_start).zfill(7)} – BL-{str(bates_start + len(messages) - 1).zfill(7)}"],
        ["Generated", datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")],
    ]
    cert_table = Table(cert_data, colWidths=[2 * inch, 4.5 * inch])
    cert_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f3f4f6")),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(cert_table)
    story.append(Spacer(1, 0.3 * inch))

    story.append(Paragraph(
        "Each message in this log was cryptographically fingerprinted using SHA-256 at the moment of capture. "
        "The hash is recorded in the immutable CoGuard database. To verify any message, compute the SHA-256 hash "
        "of the body text below and compare it to the recorded value. No message can be altered after logging.",
        body_style,
    ))
    story.append(Spacer(1, 0.2 * inch))
    story.append(Paragraph(
        "This document was generated by CoGuard for use in legal proceedings. Admissibility is subject to the "
        "rules of evidence in your jurisdiction. Consult a licensed attorney to confirm admissibility.",
        ParagraphStyle("Disclaimer", parent=body_style, textColor=colors.HexColor("#6b7280"), fontSize=8),
    ))

    story.append(PageBreak())

    # ── Page 2: Incident index (high-conflict messages) ───────────────────────
    high_conflict = [m for m in messages if (m.get("hostility_score") or 0) > 0.6]
    story.append(Paragraph("Incident Index", h2_style))
    if high_conflict:
        story.append(Paragraph(f"{len(high_conflict)} high-conflict messages (hostility > 0.6):", body_style))
        idx_data = [["Bates", "Date", "Direction", "Flags", "Hostility"]]
        for i, msg in enumerate(messages):
            if (msg.get("hostility_score") or 0) <= 0.6:
                continue
            global_idx = messages.index(msg)
            flags = msg.get("flags") or []
            if isinstance(flags, str):
                try: flags = json.loads(flags)
                except: flags = []
            idx_data.append([
                _bates_label(bates_start, global_idx),
                str(msg.get("received_at", ""))[:16],
                "← In" if msg.get("channel") == "incoming" else "→ Out",
                ", ".join(flags),
                f"{(msg.get('hostility_score') or 0):.2f}",
            ])
        idx_table = Table(idx_data, colWidths=[1.2 * inch, 1.2 * inch, 0.7 * inch, 2.3 * inch, 0.8 * inch])
        idx_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#111827")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(idx_table)
    else:
        story.append(Paragraph("No high-conflict messages in this date range.", body_style))

    story.append(PageBreak())

    # ── Pages 3+: Full chronological log ─────────────────────────────────────
    story.append(Paragraph("Complete Communication Log", h2_style))
    story.append(Spacer(1, 0.1 * inch))

    for i, msg in enumerate(messages):
        bates = _bates_label(bates_start, i)
        channel = msg.get("channel", "")
        direction = "← Received" if channel == "incoming" else "→ Sent"
        hostility = msg.get("hostility_score") or 0
        flags = msg.get("flags") or []
        if isinstance(flags, str):
            try: flags = json.loads(flags)
            except: flags = []

        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e5e7eb")))
        story.append(Spacer(1, 0.05 * inch))

        # Header row
        header_parts = [f"<b>{bates}</b>   {direction}   {str(msg.get('received_at', ''))[:16]}"]
        if hostility > 0.6:
            header_parts.append(" ⚠ HIGH CONFLICT")
        story.append(Paragraph("   ".join(header_parts), ParagraphStyle("MsgHeader", parent=body_style, fontName="Helvetica-Bold", fontSize=9)))

        if msg.get("subject"):
            story.append(Paragraph(f"Subject: {msg['subject']}", body_style))
        if msg.get("sender_id"):
            story.append(Paragraph(f"From: {msg['sender_id']}", body_style))
        if flags:
            story.append(Paragraph(f"Flags: {', '.join(flags)}", flag_style))

        body_text = (msg.get("raw_body") or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        story.append(Paragraph(body_text[:3000], body_style))

        story.append(Paragraph(f"SHA-256: {msg.get('body_sha256', '')}", mono_style))
        story.append(Spacer(1, 0.1 * inch))

    doc.build(story)
    return buf.getvalue()


def _upload_to_storage(subscriber_id: str, binder_id: str, pdf_bytes: bytes) -> str:
    """Upload PDF to Supabase Storage, return signed URL."""
    bucket = "coguard-binders"
    path = f"{subscriber_id}/{binder_id}.pdf"
    url = f"{SUPABASE_URL}/storage/v1/object/{bucket}/{path}"
    headers = {**_supabase_headers(), "Content-Type": "application/pdf"}
    res = httpx.put(url, content=pdf_bytes, headers=headers, timeout=60.0)
    if not res.is_success:
        raise RuntimeError(f"Storage upload failed: {res.status_code} {res.text[:200]}")

    # Generate signed URL (24h)
    sign_url = f"{SUPABASE_URL}/storage/v1/object/sign/{bucket}/{path}"
    sign_res = httpx.post(sign_url, headers=_supabase_headers(), json={"expiresIn": 86400}, timeout=10.0)
    if sign_res.is_success:
        data = sign_res.json()
        return f"{SUPABASE_URL}/storage/v1{data.get('signedURL', '')}"
    return url


@app.post("/generate")
async def generate_binder(
    request: Request,
    x_internal_secret: str | None = Header(default=None, alias="x-internal-secret"),
) -> JSONResponse:
    _verify_secret(x_internal_secret)

    payload = await request.json()
    binder_id: str = payload.get("binder_id", "")
    subscriber_id: str = payload.get("subscriber_id", "")
    date_from: str = payload.get("date_from", "")
    date_to: str = payload.get("date_to", "")

    if not binder_id or not subscriber_id or not date_from or not date_to:
        raise HTTPException(status_code=400, detail="binder_id, subscriber_id, date_from, date_to required")

    # Update status → generating
    httpx.patch(
        f"{SUPABASE_URL}/rest/v1/coguard_binders?id=eq.{binder_id}",
        headers=_supabase_headers(),
        json={"status": "generating"},
        timeout=10.0,
    )

    try:
        # Fetch messages in date range
        url = (
            f"{SUPABASE_URL}/rest/v1/coguard_messages"
            f"?subscriber_id=eq.{subscriber_id}"
            f"&received_at=gte.{date_from}&received_at=lte.{date_to}"
            f"&order=received_at.asc"
        )
        msg_res = httpx.get(url, headers=_supabase_headers(), timeout=30.0)
        messages: list[dict] = msg_res.json() if msg_res.is_success else []

        # Determine Bates start — max existing end + 1 for this subscriber
        max_res = httpx.get(
            f"{SUPABASE_URL}/rest/v1/coguard_binders?subscriber_id=eq.{subscriber_id}&select=bates_end&order=bates_end.desc&limit=1",
            headers=_supabase_headers(),
            timeout=10.0,
        )
        bates_start = 1
        if max_res.is_success and max_res.json():
            last_end = max_res.json()[0].get("bates_end") or 0
            bates_start = last_end + 1

        pdf_bytes = _build_pdf(subscriber_id, binder_id, date_from, date_to, messages, bates_start)
        pdf_url = _upload_to_storage(subscriber_id, binder_id, pdf_bytes)

        # Generate attorney access code (random 8-char hex)
        import secrets
        attorney_code = secrets.token_hex(6)

        # Update binder → ready
        httpx.patch(
            f"{SUPABASE_URL}/rest/v1/coguard_binders?id=eq.{binder_id}",
            headers=_supabase_headers(),
            json={
                "status": "ready",
                "pdf_url": pdf_url,
                "message_count": len(messages),
                "bates_start": bates_start,
                "bates_end": bates_start + len(messages) - 1,
                "completed_at": datetime.now(timezone.utc).isoformat(),
                "attorney_access_code": attorney_code,
            },
            timeout=10.0,
        )

        # Notify subscriber
        if RESEND_API_KEY:
            sub_res = httpx.get(
                f"{SUPABASE_URL}/rest/v1/coguard_subscribers?id=eq.{subscriber_id}&select=email",
                headers=_supabase_headers(),
                timeout=10.0,
            )
            if sub_res.is_success and sub_res.json():
                email = sub_res.json()[0].get("email")
                if email:
                    body = (
                        f"Your CoGuard court binder is ready.\n\n"
                        f"Messages: {len(messages)}\n"
                        f"Bates range: BL-{str(bates_start).zfill(7)} – BL-{str(bates_start + len(messages) - 1).zfill(7)}\n\n"
                        f"Download (valid 24h): {pdf_url}\n\n"
                        f"Attorney access link (share with your attorney):\n"
                        f"https://coguard.bizlegal-ai.com/attorney/{attorney_code}\n\n"
                        f"— CoGuard"
                    )
                    httpx.post(
                        "https://api.resend.com/emails",
                        headers={"Authorization": f"Bearer {RESEND_API_KEY}", "Content-Type": "application/json"},
                        json={"from": RESEND_FROM, "to": [email], "subject": "Your CoGuard court binder is ready", "text": body},
                        timeout=15.0,
                    )

        logger.info("[coguard-binder] binder %s done: %d messages, bates %d–%d", binder_id, len(messages), bates_start, bates_start + len(messages) - 1)
        return JSONResponse({"ok": True, "binder_id": binder_id, "message_count": len(messages), "pdf_url": pdf_url})

    except Exception as e:
        logger.error("[coguard-binder] error: %s", e)
        httpx.patch(
            f"{SUPABASE_URL}/rest/v1/coguard_binders?id=eq.{binder_id}",
            headers=_supabase_headers(),
            json={"status": "failed"},
            timeout=10.0,
        )
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/health")
def health() -> JSONResponse:
    return JSONResponse({"status": "ok", "service": "coguard-binder", "port": 8083})


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    uvicorn.run(app, host="0.0.0.0", port=8083)
