import type { Metadata, Viewport } from "next"
import type { ReactNode } from "react"

export const metadata: Metadata = {
  title: "DealDesk — lease abstracts and closing checklists",
  description:
    "Abstract a lease into structured critical dates, and run a closing checklist with a deadline engine. One workspace, one property record.",
  robots: { index: false, follow: false },
}

export const viewport: Viewport = { width: "device-width", initialScale: 1 }

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        style={{
          margin: 0,
          background: "#0b0d12",
          color: "#e8e6e3",
          fontFamily:
            "ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif",
        }}
      >
        {children}
        <footer
          style={{
            borderTop: "1px solid #1e2430",
            marginTop: "4rem",
            padding: "2rem 1.5rem",
            fontSize: "0.8rem",
            lineHeight: 1.6,
            color: "#8b93a7",
          }}
        >
          DealDesk is software that organizes document and public information into
          structured formats. It does not practise law, render legal advice, create an
          attorney-client relationship, or substitute for physical inspection,
          appraisal, title opinion, escrow services, or qualified counsel. All output
          is generated by automated systems for informational purposes only. You are
          responsible for decisions made using it.
        </footer>
      </body>
    </html>
  )
}
