export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-12">
      <h1 className="text-3xl font-bold text-white mb-8">Terms of Service</h1>
      <div className="prose prose-invert max-w-none space-y-6 text-forge-muted text-sm leading-relaxed">
        <p><strong>Last updated:</strong> April 2, 2026</p>

        <h2 className="text-xl font-bold text-white mt-8 mb-3">1. Acceptance of Terms</h2>
        <p>By accessing or using Forge Compliance Engine (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>

        <h2 className="text-xl font-bold text-white mt-8 mb-3">2. Nature of Service</h2>
        <p>The Service provides regulatory intelligence and compliance analysis powered by artificial intelligence. <strong>All reports are for informational purposes only and do not constitute legal advice.</strong> You should consult qualified legal counsel before making any compliance decisions.</p>

        <h2 className="text-xl font-bold text-white mt-8 mb-3">3. User Obligations</h2>
        <p>You agree to provide accurate and complete information when using the Service. You are responsible for maintaining the confidentiality of your account and payment information.</p>

        <h2 className="text-xl font-bold text-white mt-8 mb-3">4. Payment and Refunds</h2>
        <p>Payment is required for full reports. We accept cryptocurrency (via NOWPayments) and card payments (via Payoneer). Refunds are available within 7 days if no compliance issues are found or if you&apos;re unsatisfied with report quality. See our Refund Policy for details.</p>

        <h2 className="text-xl font-bold text-white mt-8 mb-3">5. Intellectual Property</h2>
        <p>All reports, analysis, and content generated by the Service are licensed (not sold) to you for your internal business use. You may not resell, redistribute, or publicly share reports without written consent.</p>

        <h2 className="text-xl font-bold text-white mt-8 mb-3">6. Limitation of Liability</h2>
        <p>The Service is provided &quot;as is&quot; without warranties of any kind. Forge Compliance Engine and BizLegal AI shall not be liable for any damages arising from use of the Service, including but not limited to regulatory penalties, legal costs, or business losses.</p>

        <h2 className="text-xl font-bold text-white mt-8 mb-3">7. Data Privacy</h2>
        <p>We collect and process personal data as described in our Privacy Policy. By using the Service, you consent to such processing.</p>

        <h2 className="text-xl font-bold text-white mt-8 mb-3">8. Governing Law</h2>
        <p>These Terms are governed by the laws of the State of Delaware, United States. Any disputes shall be resolved in the courts of Delaware.</p>

        <h2 className="text-xl font-bold text-white mt-8 mb-3">9. Changes to Terms</h2>
        <p>We reserve the right to modify these Terms at any time. Continued use of the Service after changes constitutes acceptance of the new Terms.</p>

        <h2 className="text-xl font-bold text-white mt-8 mb-3">10. Contact</h2>
        <p>For questions about these Terms, contact us at <a href="mailto:support@bizlegal-ai.com" className="text-forge-accent">support@bizlegal-ai.com</a>.</p>
      </div>
    </div>
  )
}
