-- enable_rls_all_public_tables.sql
-- Auto-generated by supabase_rls_audit.py 2026-07-07
-- Project: bizlegal-ai (ydghhcuuopqzgqcicubg)
-- Action: enable RLS on every public schema table
--
-- Supabase flagged "Table publicly accessible" (rls_disabled_in_public).
-- The PostgREST API exposes all 89 public tables. The service role key still
-- bypasses RLS, so the app keeps working. The anon role (browser, public)
-- will start getting empty results until proper policies are added.
--
-- IMPORTANT: This only enables RLS. It does NOT add policies. The next step
-- is to add policies per table. Most tables are write-only-from-service-role
-- (event logs, snapshots, lead pipeline), so a permissive "service role only"
-- policy is the right pattern. For user-facing tables (users, profiles,
-- subscriptions, conductor_*) the existing app code may rely on anon reads
-- — that code will break and needs review.
--
-- Run via Supabase SQL editor (https://supabase.com/dashboard/project/ydghhcuuopqzgqcicubg/sql)
-- or via psql:
--   PGPASSWORD=*** psql "postgresql://postgres:[PASSWORD]@db.ydghhcuuopqzgqcicubg.supabase.co:5432/postgres" -f enable_rls_all_public_tables.sql

DO $$
DECLARE
    t text;
    tables text[] := ARRAY[
        'affiliate_clicks',
        'affiliates',
        'agent_runs',
        'ai_act_classifications',
        'ai_act_framework_index',
        'ai_act_subs',
        'ai_logs',
        'assessments',
        'audit_logs',
        'automation_state',
        'boi_orders',
        'boi_rule_index',
        'boi_subscriptions',
        'cert_payment_intents',
        'certificates',
        'cle_enrollments',
        'compliance_framework_index',
        'compliance_snapshots',
        'compliance_subs',
        'conductor_firm_kb',
        'conductor_kb',
        'conductor_profiles',
        'conductor_reports',
        'conductor_reviews',
        'contract_scans',
        'contracts',
        'conversion_snapshots',
        'crypto_scans',
        'daily_gaps',
        'deal_rooms',
        'deal_router_active',
        'deal_router_leads',
        'dunning_queue',
        'fc_approvals',
        'fc_audits',
        'fc_content',
        'fc_conversations',
        'fc_deals',
        'fc_email_log',
        'fc_leads',
        'fc_orders',
        'fc_processed_events',
        'fc_signals',
        'firms',
        'forge_scans',
        'gap_pages',
        'inbound_leads',
        'intelligence_products',
        'lead_magnets',
        'lead_nurture_state',
        'lead_outreach',
        'leadforge_leads',
        'leads',
        'leads_clean',
        'leads_raw',
        'lexaudit_certificates',
        'matters',
        'newsletter_subscribers',
        'ops_events',
        'ops_events_24h_by_type',
        'ops_events_recent',
        'page_enrichments',
        'partner_outreach',
        'partners',
        'payment_orders',
        'payouts',
        'payouts_open',
        'policy_refresh_audits',
        'policy_refresh_subs',
        'processed_webhook_events',
        'product_orders',
        'profiles',
        'purchases',
        'risk_snapshots',
        'sanctions_cache',
        'scans',
        'seo_pages',
        'social_drafts',
        'sqa_firm_kb_items',
        'subscribers',
        'subscriptions',
        'tracr_orders',
        'tracr_wallet_leads',
        'trcr_activities',
        'trcr_clients',
        'trcr_deals',
        'trcr_documents',
        'users',
        'verticals'
    ];
    rls_off_count int := 0;
    rls_already_on_count int := 0;
BEGIN
    FOREACH t IN ARRAY tables LOOP
        -- Check if table exists
        IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='public' AND tablename=t) THEN
            IF NOT EXISTS (
                SELECT 1 FROM pg_class c
                JOIN pg_namespace n ON n.oid = c.relnamespace
                WHERE n.nspname='public' AND c.relname=t AND c.relrowsecurity = true
            ) THEN
                EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
                rls_off_count := rls_off_count + 1;
                RAISE NOTICE 'ENABLED RLS on public.%', t;
            ELSE
                rls_already_on_count := rls_already_on_count + 1;
            END IF;
        ELSE
            RAISE NOTICE 'SKIP — public.% does not exist', t;
        END IF;
    END LOOP;
    RAISE NOTICE 'SUMMARY: % tables had RLS enabled, % were already protected', rls_off_count, rls_already_on_count;
END
$$;

-- ────────────────────────────────────────────────────────────────
-- SECTION 2 (added 2026-07-08): policies for tables the browsers
-- actually read/write with the ANON/authenticated key. Without these,
-- enabling RLS blanks the DocAI Conductor dashboard, the LexAudit
-- dashboard + matter flows, and the PUBLIC certificate share pages.
-- Traced from source:
--   apps/docai/web/app/dashboard/**      → conductor_reports, conductor_reviews (read, logged-in)
--   apps/lexaudit/app/certificate/[id]   → certificates (read, ANON — public share page by design)
--   apps/lexaudit/app/dashboard          → subscriptions (read), matters (read/insert)
--   apps/lexaudit/app/matter/[id]        → matters (read/update), ai_logs (read/insert)
-- These preserve the exact status-quo access (which was fully public)
-- for only these flows — a strict security improvement on the other
-- 80+ tables. Tighten per-user scoping as a follow-up.
-- ────────────────────────────────────────────────────────────────

-- Public certificate share pages (cert id in URL is the access token)
DROP POLICY IF EXISTS "public read certificates" ON public.certificates;
CREATE POLICY "public read certificates" ON public.certificates
  FOR SELECT TO anon, authenticated USING (true);

-- Logged-in DocAI Conductor dashboard
DROP POLICY IF EXISTS "authenticated read conductor_reports" ON public.conductor_reports;
CREATE POLICY "authenticated read conductor_reports" ON public.conductor_reports
  FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "authenticated read conductor_reviews" ON public.conductor_reviews;
CREATE POLICY "authenticated read conductor_reviews" ON public.conductor_reviews
  FOR SELECT TO authenticated USING (true);

-- Logged-in LexAudit dashboard + matter workflow
DROP POLICY IF EXISTS "authenticated read subscriptions" ON public.subscriptions;
CREATE POLICY "authenticated read subscriptions" ON public.subscriptions
  FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "authenticated all matters" ON public.matters;
CREATE POLICY "authenticated all matters" ON public.matters
  FOR ALL TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "authenticated all ai_logs" ON public.ai_logs;
CREATE POLICY "authenticated all ai_logs" ON public.ai_logs
  FOR ALL TO authenticated USING (true) WITH CHECK (true);
