/**
 * PDF report builder — uses pdfkit to render the full paid report.
 * Stores to Supabase Storage under funnel-uploads/reports/<jobId>.pdf
 * and returns the storage key (NOT a signed URL; the route generates a
 * fresh 1-hour signed URL each time the user requests it).
 */

import PDFDocument from 'pdfkit'
import type { ExtractionResult, Issue } from './ai/schema'
import { serviceSupabase, STORAGE_BUCKET } from './supabase'

export interface BuildReportArgs {
  readonly jobId: string
  readonly userEmail: string
  readonly filename: string
  readonly extraction: ExtractionResult
}

export async function buildAndUploadReport(args: BuildReportArgs): Promise<string> {
  const pdfBuffer = await renderPdf(args)
  const supabase = serviceSupabase()
  const storageKey = `reports/${args.jobId}.pdf`
  const { error } = await supabase.storage
    .from(STORAGE_BUCKET)
    .upload(storageKey, pdfBuffer, {
      contentType: 'application/pdf',
      upsert: true,
    })
  if (error) throw new Error(`storage upload failed: ${error.message}`)
  return storageKey
}

function renderPdf(args: BuildReportArgs): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50 })
      const chunks: Buffer[] = []
      doc.on('data', (c: Buffer) => chunks.push(c))
      doc.on('end', () => resolve(Buffer.concat(chunks)))
      doc.on('error', reject)

      // Header
      doc.fontSize(20).fillColor('#0f172a').text('BizLegal AI — Contract Risk Report', { align: 'left' })
      doc.moveDown(0.5)
      doc.fontSize(10).fillColor('#64748b').text(`Job ID: ${args.jobId}`, { align: 'left' })
      doc.text(`Document: ${args.filename}`, { align: 'left' })
      doc.text(`Recipient: ${args.userEmail}`, { align: 'left' })
      doc.text(`Generated: ${new Date().toISOString()}`, { align: 'left' })
      doc.moveDown(1)

      // Overall summary
      doc.fontSize(14).fillColor('#0f172a').text('Overall Risk Assessment', { underline: false })
      doc.moveDown(0.3)
      doc.fontSize(11).fillColor(severityColor(args.extraction.overall_risk)).text(args.extraction.overall_risk.toUpperCase(), { continued: true })
      doc.fontSize(11).fillColor('#0f172a').text(`  ·  ${args.extraction.summary}`)
      doc.moveDown(1)

      renderSection(doc, 'Anomalies', args.extraction.anomalies)
      renderSection(doc, 'Missing Protections', args.extraction.missing_protections)
      renderSection(doc, 'Ambiguities', args.extraction.ambiguities)
      renderSection(doc, 'Notable Clauses', args.extraction.clauses)

      // Footer disclaimer
      doc.moveDown(2)
      doc.fontSize(9).fillColor('#94a3b8').text(
        'BizLegal AI provides decision-support, not legal advice. This report is generated by AI from the uploaded document. For a binding opinion, consult a licensed attorney in your jurisdiction. © 2026 DOR INNOVATIONS.',
        { align: 'left' },
      )

      doc.end()
    } catch (err) {
      reject(err)
    }
  })
}

function renderSection(doc: PDFKit.PDFDocument, title: string, items: ReadonlyArray<Issue>): void {
  if (items.length === 0) return
  doc.moveDown(0.5)
  doc.fontSize(13).fillColor('#0f172a').text(`${title} (${items.length})`)
  doc.moveDown(0.3)
  for (const item of items) {
    doc.fontSize(11).fillColor(severityColor(item.severity)).text(`[${item.severity.toUpperCase()}] `, { continued: true })
    doc.fontSize(11).fillColor('#0f172a').text(item.title)
    doc.fontSize(10).fillColor('#475569').text(item.detail, { indent: 12 })
    doc.moveDown(0.4)
  }
}

function severityColor(s: string): string {
  return s === 'high' ? '#dc2626' : s === 'medium' ? '#d97706' : '#16a34a'
}
