import Link from 'next/link'

export const metadata = {
  title: 'Disclaimer | TRACR — Powered by BizLegal AI',
  description: 'Legal disclaimer for TRACR regulatory risk intelligence platform by BizLegal AI (bizlegal-ai.com).',
}

const s = { minHeight: '100vh', background: '#0b1326', color: '#dae2fd', fontFamily: "'DM Sans', sans-serif", padding: '80px 32px' } as const
const inner = { maxWidth: '720px', margin: '0 auto' } as const
const h1 = { fontSize: '36px', fontWeight: 800, marginBottom: '8px', color: '#f0f2ff' } as const
const meta = { fontSize: '12px', color: '#636680', marginBottom: '40px' } as const
const h2 = { fontSize: '18px', fontWeight: 600, color: '#f0f2ff', marginBottom: '10px', marginTop: '32px' } as const
const p = { fontSize: '14px', color: '#94a3b8', lineHeight: 1.8, marginBottom: '20px' } as const
const a = { color: '#a5b4fc', textDecoration: 'none' } as const
const warn = { background: 'rgba(239,68,68,0.1)', border: '1px solid rgba(239,68,68,0.3)', borderRadius: '12px', padding: '24px', marginBottom: '32px' } as const

export default function DisclaimerPage() {
  return (
    <div style={s}><div style={inner}>
      <h1 style={h1}>Legal Disclaimer</h1>
      <p style={{ fontSize: '13px', color: '#a5b4fc', marginBottom: '4px' }}>TRACR — Powered by <a href="https://bizlegal-ai.com" style={a}>BizLegal AI</a> (bizlegal-ai.com)</p>
      <p style={meta}>Last updated: April 2026</p>
      <div style={warn}>
        <p style={{ color: '#f87171', fontWeight: 700, fontSize: '16px', marginBottom: '8px' }}>⚠️ IMPORTANT: NOT LEGAL ADVICE</p>
        <p style={{ color: '#fca5a5', fontSize: '14px', lineHeight: 1.6 }}>TRACR provides regulatory risk intelligence, not legal advice. All reports are generated by AI and are for informational purposes only.</p>
      </div>
      <h2 style={h2}>1. No Attorney-Client Relationship</h2>
      <p style={p}>Use of TRACR does not create an attorney-client relationship. For legal advice regarding regulatory compliance, consult a licensed attorney.</p>
      <h2 style={h2}>2. AI-Generated Analysis</h2>
      <p style={p}>Reports are generated using artificial intelligence (Anthropic Claude) combined with regulatory databases. AI-generated content may contain errors or omissions. Risk scores are estimates, not guarantees.</p>
      <h2 style={h2}>3. Regulatory Information</h2>
      <p style={p}>Regulatory frameworks change frequently. Our analysis reflects the landscape at time of generation and may not account for recent changes. Always verify with current regulations.</p>
      <h2 style={h2}>4. Limitation of Liability</h2>
      <p style={p}>TRACR and BizLegal AI shall not be liable for any damages arising from reliance on report content, including regulatory penalties, legal costs, or financial losses.</p>
      <h2 style={h2}>5. Contact</h2>
      <p style={p}>Questions: <a href="mailto:team@bizlegal-ai.com" style={a}>team@bizlegal-ai.com</a></p>
      <div style={{ borderTop: '1px solid #1e293b', marginTop: '40px', paddingTop: '20px', display: 'flex', gap: '24px' }}>
        <Link href="/terms" style={a}>← Terms of Service</Link>
        <Link href="/privacy" style={a}>Privacy Policy →</Link>
      </div>
    </div></div>
  )
}
